### ISSUE TITLE
Any related paper or document?

### ISSUE THREAD

**Issue by Taeyoung96** [nkymzsy/RI-OM#1]
@nkymzsy   
Thanks for sharing your great work.  
What is the difference between the original LeGO-LOAM?  
Is there any related paper or document?  

Thanks,

**Comment by nkymzsy** [comment]
> 
Thank you for your attention. The paper for this code is not currently published (which is a sad story). But this code is inspired by [LiTAMIN: LiDAR-based Tracking And Mapping by Stabilized ICP for Geometry Approximation with Normal Distributions](https://ieeexplore.ieee.org/document/9341341). Due to level limits, this code may only be at the level of a hands-on project.

**Comment by Taeyoung96** [comment]
@nkymzsy   
I'm sorry to hear that...   
But I cheer you to do better research based on this wonderful code. Thank you for your reply.
